### ISSUE TITLE
Needs HTTPS

### ISSUE THREAD

**Issue by ajacques** [mtimkovich/maxtimkovich.com#1]
The website currently is not protected by any encryption or authentication. HTTPS should be a necessity in any serious website in 2017. Please consider enabling HTTPS. There are many great tools that can manage this for you, such as this one that's used by almost every major* website: https://github.com/ajacques/CertManager.

All links should use https://, should use Key Pinning, and HSTS.

**Comment by mtimkovich** [comment]
Thank you for your suggestion Mr. Jacques! You will be pleased to know that https://maxtimkovich.com now has TLS support on all of its pages!

Thank you for your continued support!

**Comment by ajacques** [comment]
Great work I feel safer already. I do note that you haven't enabled the HTTP Strict Transport Security headers. These are a must to ensure that a client doesn't accidentally navigate to HTTP.
